.Dd $Mdocdate$
.Dt TPKG_RM 1
.Os
.Sh NAME
.Nm tpkg_rm
.Nd remove software packages
.Sh SYNOPSIS
.Nm tpkg_rm
.Bk -words
.Op Fl options
.Op Ar pkg-name ...
.Ek
.Sh DESCRIPTION
.Sh FILES
.Sh EXIT STATUS
.Ex -std tpkg_rm
.Sh EXAMPLES
.Sh DIAGNOSTICS
.Sh ERRORS
.Sh SEE ALSO
.Xr tpkg_add 1
.Sh AUTHORS
.An d0p1 Aq Mt contact@d0p1.eu
